### ISSUE TITLE
check LaserFlipped flag when publishing laserscan topic?

### ISSUE THREAD

**Issue by reed-adept** [MobileRobots/ros-arnl#12]

**Comment by reed-adept** [comment]
or perhaps explain how to use laser_filters to do it?

**Comment by RobertBlakeAnderson** [comment]
Would this work to handle flipped data in LaserPublisher.cpp?

```
void LaserPublisher::publishLaserScan()
{
  laserscan.header.stamp = convertArTimeToROS(laser->getLastReadingTime());
  const std::list<ArSensorReading*> *readings = laser->getRawReadings(); 
  assert(readings);
  //printf("laserscan: %lu readings\n", readings->size());

  laserscan.ranges.resize(readings->size());

  size_t n = 0;
  if (laser->getFlipped()) {
    for(std::list<ArSensorReading*>::const_reverse_iterator r = readings->rbegin(); r != readings->rend(); ++r)
    {
      assert(*r);
      //printf("range %dmm extra %d\n", (*r)->getRange(), (*r)->getExtraInt());
      laserscan.ranges[n] = (*r)->getRange() / 1000.0;
      //laserscan.intensities[n] = (*r)->getExtraInt();
      ++n;
    }
  }
  else {
    for(std::list<ArSensorReading*>::const_iterator r = readings->begin(); r != readings->end(); ++r)
    {
      assert(*r);
      //printf("range %dmm extra %d\n", (*r)->getRange(), (*r)->getExtraInt());
      laserscan.ranges[n] = (*r)->getRange() / 1000.0;
      //laserscan.intensities[n] = (*r)->getExtraInt();
      ++n;
    }
  }

  laserscan_pub.publish(laserscan);
}
```

**Comment by reed-adept** [comment]
Seem like that should do it...   maybe there is a way to avoid duplicating the loop, not sure how unless const_reverse_iterator and const_iterator are compatible in some way... hmm.  Do angle_min and angle_max in the message need to be swapped?

**Comment by RobertBlakeAnderson** [comment]
std::list has a reverse() function that could be used instead of the reverse iterator. That will be more expensive than the code above, though, and time optimization should be prioritized for this function.

reverse_iterator does inherit from iterator, so you could maybe set up a polymorphic loop. Ultimately I doubt it would actually be more compact or than just repeating the loop though, it's just a few lines after all. And it would likely be less readable.

I wouldn't think the angles need to be swapped, but that can be tested once the angle increment issue is also fixed.
